# This script automates the reconciliation of bank and auxiliary financial records by comparing transaction data 
# and generating an Excel report highlighting matches and inconsistencies.

# External libraries
import pandas as pd

# Local Modules for Data Extraction
import PDF2Excel as P2E
import PDF2Excel_Extraction as P2EE
import Excel_Extraction as Excel

# INSERT DATA HERE  :D
"""
To identify financial transactions, we need to detect the keywords in the PDF content. When one of these keywords is found in a line,
it indicates a value that should be recorded. The keywords are divided into two categories: Incomes and Outcomes.

List of keywords (EXAMPLE):

Income:
- Sales_Product (P1)

Outcome:
- Comission (C1)
"""

# PDF2Excel
PDF_path = "My_path_to_PDF_register.pdf"            # Path to the PDF file

key_words = ["Sales_Product",                       # Keywords for Incomes

            "Comission",]                           # Keywords for Outcomes

PDF_Excel_path = "PDF2Excel.xlsx"                   # Output Excel file from PDF processing

# PDF2Excel_Extraction
key_words_Ingresos = ["P1"]                         # Income keywords
key_words_Egresos = ["C1"]                          # Outcome keywords

# Columns in the processed PDF (Excel)
PDF_Columna_para_fechas = 0                         # Column for transaction dates
PDF_Columna_para_movimientos = 1                    # Column for transaction amounts
PDF_Columna_para_referencias = 2                    # Column for References data
PDF_Columna_para_beneficiario = 3                   # Column for Beneficiary data
PDF_HEADER = 2                                      # Rows over the table unnecessary for analysis
    
# Excel_Extraction
Excel_path = "My_path_to_Auxiliary_register.xlsx"   # Path to the Excel file
Columna_para_fechas = 0                             # Column for Dates data
Columna_para_beneficiario = 5                       # Column for Beneficiary data
Columna_para_referencias = 7                        # Column for References data
Columna_para_ingresos = 9                           # Column for Incomes data
Columna_para_egresos = 8                            # Column for Outcomes data
HEADER = 18                                         # Rows over the table unnecessary for analysis

# MAIN
    
Nombre_del_archivo_de_salida = 'Results.xlsx'       # Name of Excel File generated by the program
Margen_de_error = 1                                 # Error Margin of One Unit (Mexican Peso)
Margen_de_error_temporal = 3                        # Error Margin of three days


# Beginning of the reconciliation algorithm

# Functions

def Comparador(Lista_de_valores_Banco, Lista_de_Fechas_Banco, Lista_de_valores_Auxiliar, Lista_de_Fechas_Auxiliar, Valores_en_ambas_listas, Fechas_en_ambas_listas, Valores_en_ninguna_lista, Fechas_en_ninguna_lista, Referencias, Beneficiarios):
    
    """
    Compares two lists of financial transactions (bank vs auxiliary data) to identify matches and inconsistencies.
    
    Parameters:
    - Lista_de_valores_Banco: List of monetary values from the bank records.
    - Lista_de_Fechas_Banco: List of corresponding transaction dates from the bank records.
    - Lista_de_valores_Auxiliar: List of monetary values from auxiliary records (e.g., Excel).
    - Lista_de_Fechas_Auxiliar: List of corresponding transaction dates from auxiliary records.
    - Valores_en_ambas_listas: List to store matching monetary values.
    - Fechas_en_ambas_listas: List to store matching transaction dates.
    - Valores_en_ninguna_lista: List to store unmatched monetary values.
    - Fechas_en_ninguna_lista: List to store unmatched transaction dates.
    - Referencias: List of transaction references from bank records.
    - Beneficiarios: List of beneficiaries associated with transactions in bank records.
    """
   
    for i, A in enumerate(Lista_de_valores_Banco):
    
        fecha_A = Lista_de_Fechas_Banco[i]
        Found = False

        for j, B in enumerate(Lista_de_valores_Auxiliar):
       
            fecha_B = Lista_de_Fechas_Auxiliar[j]

            if fechas_dentro_del_margen(fecha_A, fecha_B, Margen_de_error_temporal) and valores_dentro_del_margen(A, B, Margen_de_error) and (A not in Valores_en_ambas_listas or Lista_de_Fechas_Banco[i] not in Fechas_en_ambas_listas or Lista_de_valores_Banco.count(A) > 1):

                # Match found
                Valores_en_ambas_listas.append(A)
                Fechas_en_ambas_listas.append(fecha_A)
                Found = True
                print(f"\033[1mConsistente     Banco  |  Auxiliar \033[0m ")
                print(f"Cantidad:     {A}  -  {B}  ")
                print(f"Fecha:      {fecha_A}   -   {fecha_B}")
                print("")

                # Mark the record as matched in auxiliary data
                Lista_de_valores_Auxiliar[j] = 0
                Referencias[i] = "0"
                Beneficiarios[i] = "0"
                break

        if not Found:
            # Record is inconsistent
            Valores_en_ninguna_lista.append(A)
            Fechas_en_ninguna_lista.append(fecha_A)
            print(f"\033[1mInconsistente:\033[0m {A}")
            print(f"Fecha: {Lista_de_Fechas_Banco[i]}")
            print("")
           
    print("")
    print("-------------------------------------------------------------------------------------------------")
    print("")
        
    return Valores_en_ambas_listas, Fechas_en_ambas_listas, Valores_en_ninguna_lista, Fechas_en_ninguna_lista

def fechas_dentro_del_margen(fecha1, fecha2, margen):
    """
    Checks if two dates are within the specified margin of error.
    """
    return abs(fecha1 - fecha2) <= margen or abs(fecha1 - fecha2) == 0 

def valores_dentro_del_margen(valor1, valor2, margen):
    """
    Checks if two monetary values are within the specified margin of error.
    """
    return abs(valor1 - valor2) <= margen

def Dataframe_Construction(Fechas_en_ninguna_lista, valores_en_ninguna_lista, Referencias, Beneficiarios):
    """
    Creates a DataFrame for inconsistent records.
    """    
    Inconsistencias_Dataframe = {
    'Fechas': Fechas_en_ninguna_lista,
    'Importe': valores_en_ninguna_lista,
    'Referencias': Referencias, 
    'Beneficiario / Ordenante': Beneficiarios}
    
    Inconsistencias_Dataframe = pd.DataFrame(Inconsistencias_Dataframe)
    
    return Inconsistencias_Dataframe

def Excel_Construction(Table_title, Tabla_Inconsistencias):
    """
    Constructs an Excel-compatible DataFrame with a general header and inconsistency data.
    """    
    General_header = pd.DataFrame([[Table_title, "", "", ""]],
    columns = ['Fechas', 'Importe', 'Referencias', 'Beneficiario / Ordenante'])
    
    Tabla_Inconsistencias_Excel = pd.concat([General_header, Tabla_Inconsistencias], ignore_index = True)
    
    return Tabla_Inconsistencias_Excel

# Data Set-up
"""
1. PDF to Excel conversion
2. Data extraction of converted PDF (Excel)
3. Excel data extraction
"""

PDF2Excel = P2E.PDF2Excel(PDF_path, key_words, PDF_Excel_path)
Lista_de_valores_MNA_BBVA_Ingresos, Lista_de_valores_MNA_BBVA_Egresos, Lista_de_valores_MNA_BBVA_Fechas_Ingresos, Lista_de_valores_MNA_BBVA_Fechas_Egresos, Referencias_MNA_BBVA_Ingresos, Referencias_MNA_BBVA_Egresos, Beneficiarios_MNA_BBVA_Ingresos, Beneficiarios_MNA_BBVA_Egresos = P2EE.Value_extraction(key_words_Ingresos, key_words_Egresos, PDF_Excel_path, PDF_Columna_para_fechas, PDF_Columna_para_movimientos, PDF_Columna_para_referencias, PDF_Columna_para_beneficiario, PDF_HEADER)
Lista_de_valores_Auxiliar_Ingresos, Lista_de_valores_Auxiliar_Egresos, Lista_de_valores_Auxiliar_Fechas_Ingresos, Lista_de_valores_Auxiliar_Fechas_Egresos, Referencias_Auxiliar_Ingresos, Referencias_Auxiliar_Egresos, Beneficiarios_Auxiliar_Ingresos, Beneficiarios_Auxiliar_Egresos = Excel.Value_extraction(Excel_path, Columna_para_fechas, Columna_para_beneficiario, Columna_para_referencias, Columna_para_ingresos, Columna_para_egresos, HEADER)

print("")
print("            Conciliación Bancaria")
print("")

# Variables declaration

# BBVA Income
Ingresos_en_ambas_listas_MNA_BBVA = []          # Matching income values found in both Bank and Auxiliary records
Fechas_en_ambas_listas_Ingresos_MNA_BBVA = []   # Matching income dates for the values above
Valores_en_ninguna_lista_MNA_BBVA_Ingresos = [] # Income values found only in Bank records
Fechas_en_ninguna_lista_Ingresos_MNA_BBVA = []  # Dates corresponding to income found only in Bank records

# Excel Income
Ingresos_en_ambas_listas_auxiliar = []          # Matching income values found in both Auxiliary and Bank records
Fechas_en_ambas_listas_Ingresos_auxiliar = []   # Matching income dates for the values above
Valores_en_ninguna_lista_auxiliar_Ingresos = [] # Income values found only in Auxiliary records
Fechas_en_ninguna_lista_Ingresos_auxiliar = []  # Dates corresponding to income found only in Auxiliary records

# BBVA Outcome
Egresos_en_ambas_listas_MNA_BBVA = []           # Matching outcome values found in both Bank and Auxiliary records
Fechas_en_ambas_listas_Egresos_MNA_BBVA = []    # Matching outcome dates for the values above
Valores_en_ninguna_lista_MNA_BBVA_Egresos = []  # Outcome values found only in Bank records
Fechas_en_ninguna_lista_Egresos_MNA_BBVA = []   # Dates corresponding to outcome found only in Bank records

# Excel Outcome
Egresos_en_ambas_listas_auxiliar = []           # Matching outcome values found in both Auxiliary and Bank records
Fechas_en_ambas_listas_Egresos_auxiliar = []    # Matching outcome dates for the values above
Valores_en_ninguna_lista_auxiliar_Egresos = []  # Outcome values found only in Auxiliary records
Fechas_en_ninguna_lista_Egresos_auxiliar = []   # Dates corresponding to outcome found only in Auxiliary records

#    Auxiliary variables
Lista_de_valores_Auxiliar_Ingresos_Copia = Lista_de_valores_Auxiliar_Ingresos.copy()
Lista_de_valores_Auxiliar_Egresos_Copia = Lista_de_valores_Auxiliar_Egresos.copy()
Lista_de_valores_MNA_BBVA_Ingresos_Copia = Lista_de_valores_MNA_BBVA_Ingresos.copy()
Lista_de_valores_MNA_BBVA_Egresos_Copia = Lista_de_valores_MNA_BBVA_Egresos.copy()

# Work Cycle 1: Income Recorded in the Bank but not in Excel
Comparador(Lista_de_valores_MNA_BBVA_Ingresos_Copia, Lista_de_valores_MNA_BBVA_Fechas_Ingresos, Lista_de_valores_Auxiliar_Ingresos_Copia, Lista_de_valores_Auxiliar_Fechas_Ingresos, Ingresos_en_ambas_listas_MNA_BBVA, Fechas_en_ambas_listas_Ingresos_MNA_BBVA, Valores_en_ninguna_lista_MNA_BBVA_Ingresos, Fechas_en_ninguna_lista_Ingresos_MNA_BBVA, Referencias_MNA_BBVA_Ingresos, Beneficiarios_MNA_BBVA_Ingresos)

# Remove matched records from reference and beneficiary lists
Referencias_MNA_BBVA_Ingresos = [x for x in Referencias_MNA_BBVA_Ingresos if x != "0"]
Beneficiarios_MNA_BBVA_Ingresos = [x for x in Beneficiarios_MNA_BBVA_Ingresos if x != "0"]

# Generate DataFrame for inconsistencies and prepare Excel-compatible structure
Tabla_Inconsistencias_Ingresos_MNA_BBVA = Dataframe_Construction(Fechas_en_ninguna_lista_Ingresos_MNA_BBVA, Valores_en_ninguna_lista_MNA_BBVA_Ingresos, Referencias_MNA_BBVA_Ingresos, Beneficiarios_MNA_BBVA_Ingresos)
Tabla_Inconsistencias_Ingresos_MNA_BBVA = Excel_Construction("Ingresos registrados en Banco y no en Auxiliar", Tabla_Inconsistencias_Ingresos_MNA_BBVA)


# Work Cycle 2: Outcome Recorded in the Bank but not in Excel
Comparador(Lista_de_valores_MNA_BBVA_Egresos, Lista_de_valores_MNA_BBVA_Fechas_Egresos, Lista_de_valores_Auxiliar_Egresos_Copia, Lista_de_valores_Auxiliar_Fechas_Egresos, Egresos_en_ambas_listas_MNA_BBVA, Fechas_en_ambas_listas_Egresos_MNA_BBVA, Valores_en_ninguna_lista_MNA_BBVA_Egresos, Fechas_en_ninguna_lista_Egresos_MNA_BBVA, Referencias_MNA_BBVA_Egresos, Beneficiarios_MNA_BBVA_Egresos)

# Remove matched records from reference and beneficiary lists
Referencias_MNA_BBVA_Egresos = [x for x in Referencias_MNA_BBVA_Egresos if x != "0"]
Beneficiarios_MNA_BBVA_Egresos = [x for x in Beneficiarios_MNA_BBVA_Egresos if x != "0"]

# Generate DataFrame for inconsistencies and prepare Excel-compatible structure
Tabla_Inconsistencias_Egresos_MNA_BBVA = Dataframe_Construction(Fechas_en_ninguna_lista_Egresos_MNA_BBVA, Valores_en_ninguna_lista_MNA_BBVA_Egresos, Referencias_MNA_BBVA_Egresos, Beneficiarios_MNA_BBVA_Egresos)
Tabla_Inconsistencias_Egresos_MNA_BBVA = Excel_Construction("Egresos registrados en Banco y no en Auxiliar", Tabla_Inconsistencias_Egresos_MNA_BBVA)


# Work Cycle 3: Income Recorded in Excel but not in the Bank
Comparador(Lista_de_valores_Auxiliar_Ingresos, Lista_de_valores_Auxiliar_Fechas_Ingresos, Lista_de_valores_MNA_BBVA_Ingresos, Lista_de_valores_MNA_BBVA_Fechas_Ingresos, Ingresos_en_ambas_listas_auxiliar, Fechas_en_ambas_listas_Ingresos_auxiliar, Valores_en_ninguna_lista_auxiliar_Ingresos, Fechas_en_ninguna_lista_Ingresos_auxiliar, Referencias_Auxiliar_Ingresos, Beneficiarios_Auxiliar_Ingresos)

# Remove matched records from reference and beneficiary lists
Referencias_Auxiliar_Ingresos = [x for x in Referencias_Auxiliar_Ingresos if x != "0"]
Beneficiarios_Auxiliar_Ingresos = [x for x in Beneficiarios_Auxiliar_Ingresos if x != "0"]

# Generate DataFrame for inconsistencies and prepare Excel-compatible structure
Tabla_Inconsistencias_Ingresos_Auxiliar = Dataframe_Construction(Fechas_en_ninguna_lista_Ingresos_auxiliar, Valores_en_ninguna_lista_auxiliar_Ingresos, Referencias_Auxiliar_Ingresos, Beneficiarios_Auxiliar_Ingresos)
Tabla_Inconsistencias_Ingresos_Auxiliar = Excel_Construction("Ingresos registrados en Auxiliar y no en Banco", Tabla_Inconsistencias_Ingresos_Auxiliar)


# Work Cycle 4: Outcome Recorded in Excel but not in the Bank
Comparador(Lista_de_valores_Auxiliar_Egresos, Lista_de_valores_Auxiliar_Fechas_Egresos, Lista_de_valores_MNA_BBVA_Egresos, Lista_de_valores_MNA_BBVA_Fechas_Egresos, Egresos_en_ambas_listas_auxiliar, Fechas_en_ambas_listas_Egresos_auxiliar, Valores_en_ninguna_lista_auxiliar_Egresos, Fechas_en_ninguna_lista_Egresos_auxiliar, Referencias_Auxiliar_Egresos, Beneficiarios_Auxiliar_Egresos)

# Remove matched records from reference and beneficiary lists
Referencias_Auxiliar_Egresos = [x for x in Referencias_Auxiliar_Egresos if x != "0"]
Beneficiarios_Auxiliar_Egresos = [x for x in Beneficiarios_Auxiliar_Egresos if x != "0"]

# Generate DataFrame for inconsistencies and prepare Excel-compatible structure
Tabla_Inconsistencias_Egresos_Auxiliar = Dataframe_Construction(Fechas_en_ninguna_lista_Egresos_auxiliar, Valores_en_ninguna_lista_auxiliar_Egresos, Referencias_Auxiliar_Egresos, Beneficiarios_Auxiliar_Egresos)
Tabla_Inconsistencias_Egresos_Auxiliar = Excel_Construction("Egresos registrados en Auxiliar y no en Banco", Tabla_Inconsistencias_Egresos_Auxiliar)

# Excel file export
# Create a consolidated Excel file with inconsistencies organized in separate sheets
with pd.ExcelWriter(Nombre_del_archivo_de_salida) as writer:
    Tabla_Inconsistencias_Ingresos_MNA_BBVA.to_excel(writer, sheet_name = "Ingresos Banco", index = False, header = True)
    Tabla_Inconsistencias_Egresos_MNA_BBVA.to_excel(writer, sheet_name = "Egresos Banco", index = False, header = True)
    Tabla_Inconsistencias_Ingresos_Auxiliar.to_excel(writer, sheet_name = "Ingresos Auxiliar", index = False, header = True)
    Tabla_Inconsistencias_Egresos_Auxiliar.to_excel(writer, sheet_name = "Egresos Auxiliar", index = False, header = True)

print("")
print("Archivo Excel exportado con éxito") # Success message for Excel export
print("")
print("")
